// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using ejercicio14.Models;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

namespace ejercicio14.Data;

public partial class NorthwindContext : IdentityDbContext
{
    public NorthwindContext(DbContextOptions<NorthwindContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Supplier> Suppliers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
        modelBuilder.Entity<Supplier>().ToTable("Suppliers", table => table.ExcludeFromMigrations());
        Seeder.SeedingDatabase(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}